version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - 8000:5000
    volumes:
      - ./:/app

  mysqldb:
    image: mysql
    ports:
    - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_conf:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tom121

volumes:
  mysql:
  mysql_conf:
